In [1]:
!pip install numpy


In [2]:
import numpy as np

In [3]:
lst=[1,5,4,8,10]

In [4]:
np.array(lst)

array([ 1,  5,  4,  8, 10])

In [5]:
board=np.ones((8,8),dtype=int)

In [6]:
board

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [7]:
bo=np.zeros((4,4),dtype=float)

In [8]:
bo

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
np.array(board,dtype=bool)

array([[ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True]])

In [10]:
ran=np.random.randint(0,10,(5,5))

In [11]:
ran

array([[8, 5, 2, 0, 2],
       [8, 9, 3, 1, 5],
       [7, 3, 3, 8, 5],
       [6, 7, 6, 8, 2],
       [2, 7, 0, 4, 0]])